/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 18-bře-2026 14:33:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS account_accountid_seq
;

DROP SEQUENCE IF EXISTS address_addressid_seq
;

DROP SEQUENCE IF EXISTS attendance_attendanceid_seq
;

DROP SEQUENCE IF EXISTS certificate_certificateid_seq
;

DROP SEQUENCE IF EXISTS discountcode_discountcodeid_seq
;

DROP SEQUENCE IF EXISTS employee_employeeid_seq
;

DROP SEQUENCE IF EXISTS lesson_template_lesson_templateid_seq
;

DROP SEQUENCE IF EXISTS lesson_type_lesson_typeid_seq
;

DROP SEQUENCE IF EXISTS member_memberid_seq
;

DROP SEQUENCE IF EXISTS membership_membershipid_seq
;

DROP SEQUENCE IF EXISTS payment_paymentid_seq
;

DROP SEQUENCE IF EXISTS reservation_reservationid_seq
;

DROP SEQUENCE IF EXISTS scheduled_lesson_scheduled_lessonid_seq
;

DROP SEQUENCE IF EXISTS tariff_tariffid_seq
;

DROP SEQUENCE IF EXISTS trainernote_trainernoteid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Account" CASCADE
;

DROP TABLE IF EXISTS "Address" CASCADE
;

DROP TABLE IF EXISTS "Attendance" CASCADE
;

DROP TABLE IF EXISTS "Certificate" CASCADE
;

DROP TABLE IF EXISTS "Discountcode" CASCADE
;

DROP TABLE IF EXISTS "Employee" CASCADE
;

DROP TABLE IF EXISTS "Lesson_template" CASCADE
;

DROP TABLE IF EXISTS "Lesson_type" CASCADE
;

DROP TABLE IF EXISTS "Lesson_typeTariff" CASCADE
;

DROP TABLE IF EXISTS "Member" CASCADE
;

DROP TABLE IF EXISTS "Membership" CASCADE
;

DROP TABLE IF EXISTS "Payment" CASCADE
;

DROP TABLE IF EXISTS "Reservation" CASCADE
;

DROP TABLE IF EXISTS "ReservationPayment" CASCADE
;

DROP TABLE IF EXISTS "Scheduled_lesson" CASCADE
;

DROP TABLE IF EXISTS "Tariff" CASCADE
;

DROP TABLE IF EXISTS "Trainernote" CASCADE
;

/* Create Tables */

CREATE TABLE "Account"
(
	"Account_name" varchar(200) NULL,
	"Is_active" boolean NULL,
	"Is_blocked" boolean NULL,
	"Password" text NULL,
	"Role" varchar(50) NULL,
	"AccountID" integer NOT NULL   DEFAULT NEXTVAL(('"account_accountid_seq"'::text)::regclass)
)
;

CREATE TABLE "Address"
(
	"Apartment_number" smallint NULL,
	"City" varchar(200) NOT NULL,
	"House_number" smallint NOT NULL,
	"Postal_code" varchar(10) NOT NULL,
	"Region" varchar(200) NULL,
	"State" varchar(200) NOT NULL,
	"Street" varchar(200) NULL,
	"AddressID" integer NOT NULL   DEFAULT NEXTVAL(('"address_addressid_seq"'::text)::regclass),
	"EmployeeID" integer NULL,
	"MemberID" integer NULL,
	CONSTRAINT "CHK_Address_Owner" CHECK (("EmployeeID" IS NOT NULL) OR ("MemberID" IS NOT NULL))
)
;

CREATE TABLE "Attendance"
(
	"Entry_type" varchar(50) NULL,
	"Timestamp_entrance" timestamp without time zone NOT NULL,
	"Timestamp_exit" timestamp without time zone NULL,
	"AttendanceID" integer NOT NULL   DEFAULT NEXTVAL(('"attendance_attendanceid_seq"'::text)::regclass),
	"MemberID" integer NULL
)
;

CREATE TABLE "Certificate"
(
	"Acquisition_date" date NULL,
	"Certificate_number" smallint NOT NULL,
	"Description" text NULL,
	"File_path" text NULL,
	"Name" varchar(200) NOT NULL,
	"Publisher" varchar(200) NULL,
	"Type" varchar(200) NOT NULL,
	"Url" varchar(500) NULL,
	"Valid_to" date NOT NULL,
	"CertificateID" integer NOT NULL   DEFAULT NEXTVAL(('"certificate_certificateid_seq"'::text)::regclass),
	"EmployeeID" integer NULL
)
;

CREATE TABLE "Discountcode"
(
	"Discount_percent" numeric(10,2) NOT NULL,
	"Expire_date" timestamp without time zone NOT NULL,
	"Name" varchar(50) NOT NULL,
	"DiscountcodeID" smallint NOT NULL   DEFAULT NEXTVAL(('"discountcode_discountcodeid_seq"'::text)::regclass)
)
;

CREATE TABLE "Employee"
(
	"Bank_account_number" varchar(34) NOT NULL,
	"End_date" date NULL,
	"Position" varchar(200) NOT NULL,
	"Role" varchar(200) NULL,
	"Start_date" date NOT NULL,
	"Type_of_empoyment" varchar(50) NOT NULL,
	"EmployeeID" integer NOT NULL   DEFAULT NEXTVAL(('"employee_employeeid_seq"'::text)::regclass)
)
;

CREATE TABLE "Lesson_template"
(
	"Description" text NULL,
	"Duration" smallint NOT NULL,
	"Maximum_capacity" smallint NOT NULL,
	"Name" varchar(200) NOT NULL,
	"Price" numeric(10,2) NOT NULL,
	"Lesson_templateID" integer NOT NULL   DEFAULT NEXTVAL(('"lesson_template_lesson_templateid_seq"'::text)::regclass),
	"Lesson_typeID" smallint NOT NULL
)
;

CREATE TABLE "Lesson_type"
(
	"Description" text NULL,
	"Name" varchar(100) NOT NULL,
	"Lesson_typeID" smallint NOT NULL   DEFAULT NEXTVAL(('"lesson_type_lesson_typeid_seq"'::text)::regclass)
)
;

CREATE TABLE "Lesson_typeTariff"
(
	"TariffID" smallint NOT NULL,
	"Lesson_typeID" smallint NOT NULL
)
;

CREATE TABLE "Member"
(
	"Credit_balance" integer NOT NULL DEFAULT 0,
	"Email" varchar(300) NULL,
	"Entry_token" uuid NOT NULL DEFAULT gen_random_uuid(),
	"First_attendance" boolean NULL,
	"Is_active" boolean NULL,
	"Name" varchar(100) NOT NULL,
	"Phone_number" varchar(50) NULL,
	"Photo" text NULL,
	"Surname" varchar(100) NOT NULL,
	"MemberID" integer NOT NULL   DEFAULT NEXTVAL(('"member_memberid_seq"'::text)::regclass),
	"AccountID" integer NULL
)
;

CREATE TABLE "Membership"
(
	"Creation_date" date NOT NULL,
	"Is_auto_renewal" boolean NULL,
	"Valid_from" timestamp without time zone NOT NULL,
	"Valid_to" timestamp without time zone NOT NULL,
	"MembershipID" integer NOT NULL   DEFAULT NEXTVAL(('"membership_membershipid_seq"'::text)::regclass),
	"MemberID" integer NOT NULL,
	"TariffID" smallint NOT NULL
)
;

CREATE TABLE "Payment"
(
	"Amount" numeric(10,2) NULL,
	"Date" timestamp with time zone NULL,
	"Payment_details" text NULL,
	"Payment_type" varchar(50) NULL,
	"Status" varchar(50) NULL,
	"PaymentID" integer NOT NULL   DEFAULT NEXTVAL(('"payment_paymentid_seq"'::text)::regclass),
	"DiscountcodeID" smallint NULL,
	"MemberID" integer NULL,
	"MembershipID" integer NULL
)
;

CREATE TABLE "Reservation"
(
	"Attendance" boolean NULL,
	"Guest_name" varchar(200) NULL,
	"Note" text NULL,
	"Status" varchar(50) NOT NULL,
	"Timestamp_creation" timestamp without time zone NOT NULL,
	"Timestamp_change" timestamp without time zone NULL,
	"ReservationID" integer NOT NULL   DEFAULT NEXTVAL(('"reservation_reservationid_seq"'::text)::regclass),
	"MemberID" integer NOT NULL,
	"Scheduled_lessonID" integer NOT NULL
)
;

CREATE TABLE "ReservationPayment"
(
	"PaymentID" integer NULL,
	"ReservationID" integer NULL
)
;

CREATE TABLE "Scheduled_lesson"
(
	"Description" text NULL,
	"Duration" smallint NOT NULL,
	"End_time" timestamp without time zone NULL,
	"Is_private" boolean NULL,
	"Maximum_capacity" smallint NOT NULL,
	"Name" varchar(200) NOT NULL,
	"Price" numeric(10,2) NULL, /* lekce se platí přes tarify/permanentky, cena lekce se nevyžaduje. Do budoucna: pokud vyplněno, lekce bude mít vlastní cenu v kreditech (např. privátní/speciální lekce mimo tarif). */
	"Start_time" timestamp without time zone NOT NULL,
	"Status" varchar(50) NOT NULL,
	"Scheduled_lessonID" integer NOT NULL   DEFAULT NEXTVAL(('"scheduled_lesson_scheduled_lessonid_seq"'::text)::regclass),
	"EmployeeID" integer NOT NULL,
	"Lesson_templateID" integer NULL,
	"Lesson_typeID" smallint NOT NULL
)
;

CREATE TABLE "Tariff"
(
	"Description" text NULL,
	"Name" varchar(100) NOT NULL,
	"Price" numeric(10,2) NOT NULL,
	"TariffID" smallint NOT NULL   DEFAULT NEXTVAL(('"tariff_tariffid_seq"'::text)::regclass)
)
;

CREATE TABLE "Trainernote"
(
	"Created_at" timestamp without time zone NULL,
	"Text" text NULL,
	"TrainernoteID" integer NOT NULL   DEFAULT NEXTVAL(('"trainernote_trainernoteid_seq"'::text)::regclass),
	"EmployeeID" integer NULL,
	"MemberID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Account" ADD CONSTRAINT "PK_Account"
	PRIMARY KEY ("AccountID")
;

ALTER TABLE "Address" ADD CONSTRAINT "PK_Address"
	PRIMARY KEY ("AddressID")
;

ALTER TABLE "Attendance" ADD CONSTRAINT "PK_Attendance"
	PRIMARY KEY ("AttendanceID")
;

ALTER TABLE "Certificate" ADD CONSTRAINT "PK_Certificate"
	PRIMARY KEY ("CertificateID")
;

ALTER TABLE "Discountcode" ADD CONSTRAINT "PK_Discountcode"
	PRIMARY KEY ("DiscountcodeID")
;

ALTER TABLE "Employee" ADD CONSTRAINT "PK_Employee"
	PRIMARY KEY ("EmployeeID")
;

ALTER TABLE "Lesson_template" ADD CONSTRAINT "PK_Lesson_template"
	PRIMARY KEY ("Lesson_templateID")
;

ALTER TABLE "Lesson_type" ADD CONSTRAINT "PK_Lesson_type"
	PRIMARY KEY ("Lesson_typeID")
;

ALTER TABLE "Lesson_typeTariff" ADD CONSTRAINT "PK_Lesson_typeTariff"
	PRIMARY KEY ("TariffID", "Lesson_typeID")
;

ALTER TABLE "Member" ADD CONSTRAINT "PK_Member"
	PRIMARY KEY ("MemberID")
;

ALTER TABLE "Membership" ADD CONSTRAINT "PK_Membership"
	PRIMARY KEY ("MembershipID")
;

ALTER TABLE "Payment" ADD CONSTRAINT "PK_Payment"
	PRIMARY KEY ("PaymentID")
;

ALTER TABLE "Reservation" ADD CONSTRAINT "PK_Reservation"
	PRIMARY KEY ("ReservationID")
;

ALTER TABLE "Scheduled_lesson" ADD CONSTRAINT "PK_Scheduled_lesson"
	PRIMARY KEY ("Scheduled_lessonID")
;

ALTER TABLE "Tariff" ADD CONSTRAINT "PK_Tariff"
	PRIMARY KEY ("TariffID")
;

ALTER TABLE "Trainernote" ADD CONSTRAINT "PK_Trainernote"
	PRIMARY KEY ("TrainernoteID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Employee"
	FOREIGN KEY ("EmployeeID") REFERENCES "Employee" ("EmployeeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Member"
	FOREIGN KEY ("MemberID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Attendance" ADD CONSTRAINT "FK_Attendance_Member"
	FOREIGN KEY ("MemberID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Certificate" ADD CONSTRAINT "FK_Certificate_Employee"
	FOREIGN KEY ("EmployeeID") REFERENCES "Employee" ("EmployeeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Employee" ADD CONSTRAINT "FK_Employee_Member"
	FOREIGN KEY ("EmployeeID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_template" ADD CONSTRAINT "FK_Lesson_template_Lesson_type"
	FOREIGN KEY ("Lesson_typeID") REFERENCES "Lesson_type" ("Lesson_typeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_typeTariff" ADD CONSTRAINT "FK_Lesson_typeTariff_Tariff"
	FOREIGN KEY ("TariffID") REFERENCES "Tariff" ("TariffID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_typeTariff" ADD CONSTRAINT "FK_Lesson_typeTariff_Lesson_type"
	FOREIGN KEY ("Lesson_typeID") REFERENCES "Lesson_type" ("Lesson_typeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Member" ADD CONSTRAINT "FK_Member_Account"
	FOREIGN KEY ("AccountID") REFERENCES "Account" ("AccountID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Membership" ADD CONSTRAINT "FK_Membership_Member"
	FOREIGN KEY ("MemberID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Membership" ADD CONSTRAINT "FK_Membership_Tariff"
	FOREIGN KEY ("TariffID") REFERENCES "Tariff" ("TariffID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Payment_Discountcode"
	FOREIGN KEY ("DiscountcodeID") REFERENCES "Discountcode" ("DiscountcodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Payment_Member"
	FOREIGN KEY ("MemberID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Payment_Membership"
	FOREIGN KEY ("MembershipID") REFERENCES "Membership" ("MembershipID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reservation" ADD CONSTRAINT "FK_Reservation_Member"
	FOREIGN KEY ("MemberID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reservation" ADD CONSTRAINT "FK_Reservation_Scheduled_lesson"
	FOREIGN KEY ("Scheduled_lessonID") REFERENCES "Scheduled_lesson" ("Scheduled_lessonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ReservationPayment" ADD CONSTRAINT "FK_ReservationPayment_Payment"
	FOREIGN KEY ("PaymentID") REFERENCES "Payment" ("PaymentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ReservationPayment" ADD CONSTRAINT "FK_ReservationPayment_Reservation"
	FOREIGN KEY ("ReservationID") REFERENCES "Reservation" ("ReservationID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Scheduled_lesson" ADD CONSTRAINT "FK_Scheduled_lesson_Employee"
	FOREIGN KEY ("EmployeeID") REFERENCES "Employee" ("EmployeeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Scheduled_lesson" ADD CONSTRAINT "FK_Scheduled_lesson_Lesson_template"
	FOREIGN KEY ("Lesson_templateID") REFERENCES "Lesson_template" ("Lesson_templateID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Scheduled_lesson" ADD CONSTRAINT "FK_Scheduled_lesson_Lesson_type"
	FOREIGN KEY ("Lesson_typeID") REFERENCES "Lesson_type" ("Lesson_typeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Trainernote" ADD CONSTRAINT "FK_Trainernote_Employee"
	FOREIGN KEY ("EmployeeID") REFERENCES "Employee" ("EmployeeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Trainernote" ADD CONSTRAINT "FK_Trainernote_Member"
	FOREIGN KEY ("MemberID") REFERENCES "Member" ("MemberID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE account_accountid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE address_addressid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE attendance_attendanceid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE certificate_certificateid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE discountcode_discountcodeid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE employee_employeeid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE lesson_template_lesson_templateid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE lesson_type_lesson_typeid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE member_memberid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE membership_membershipid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE payment_paymentid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE reservation_reservationid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE scheduled_lesson_scheduled_lessonid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tariff_tariffid_seq INCREMENT 1 START 1
;

CREATE SEQUENCE trainernote_trainernoteid_seq INCREMENT 1 START 1
;
