/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 18-bře-2026 14:33:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS account_account_id_seq
;

DROP SEQUENCE IF EXISTS address_address_id_seq
;

DROP SEQUENCE IF EXISTS attendance_attendance_id_seq
;

DROP SEQUENCE IF EXISTS certificate_certificate_id_seq
;

DROP SEQUENCE IF EXISTS discount_code_discount_code_id_seq
;

DROP SEQUENCE IF EXISTS employee_employee_id_seq
;

DROP SEQUENCE IF EXISTS lesson_template_lesson_template_id_seq
;

DROP SEQUENCE IF EXISTS lesson_type_lesson_type_id_seq
;

DROP SEQUENCE IF EXISTS member_member_id_seq
;

DROP SEQUENCE IF EXISTS membership_membership_id_seq
;

DROP SEQUENCE IF EXISTS payment_payment_id_seq
;

DROP SEQUENCE IF EXISTS reservation_reservation_id_seq
;

DROP SEQUENCE IF EXISTS lesson_schedule_lesson_schedule_id_seq
;

DROP SEQUENCE IF EXISTS tariff_tariff_id_seq
;

DROP SEQUENCE IF EXISTS trainer_note_trainer_note_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Account" CASCADE
;

DROP TABLE IF EXISTS "Address" CASCADE
;

DROP TABLE IF EXISTS "Attendance" CASCADE
;

DROP TABLE IF EXISTS "Certificate" CASCADE
;

DROP TABLE IF EXISTS "Discount_code" CASCADE
;

DROP TABLE IF EXISTS "Employee" CASCADE
;

DROP TABLE IF EXISTS "Lesson_template" CASCADE
;

DROP TABLE IF EXISTS "Lesson_type" CASCADE
;

DROP TABLE IF EXISTS "Lesson_type_Tariff" CASCADE
;

DROP TABLE IF EXISTS "Member" CASCADE
;

DROP TABLE IF EXISTS "Membership" CASCADE
;

DROP TABLE IF EXISTS "Payment" CASCADE
;

DROP TABLE IF EXISTS "Reservation" CASCADE
;

DROP TABLE IF EXISTS "Reservation_payment" CASCADE
;

DROP TABLE IF EXISTS "Lesson_schedule" CASCADE
;

DROP TABLE IF EXISTS "Tariff" CASCADE
;

DROP TABLE IF EXISTS "Trainer_note" CASCADE
;

/* Create Tables */

CREATE TABLE "Account"
(
	"Account_name" varchar(200) NULL,
	"Is_active" boolean NULL,
	"Is_blocked" boolean NULL,
	"Password" text NULL,
	"Role" varchar(50) NULL,
	"Account_ID" integer NOT NULL   DEFAULT NEXTVAL(('"account_account_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Address"
(
	"Apartment_number" smallint NULL,
	"City" varchar(200) NOT NULL,
	"House_number" smallint NOT NULL,
	"Postal_code" varchar(10) NOT NULL,
	"Region" varchar(200) NULL,
	"State" varchar(200) NOT NULL,
	"Street" varchar(200) NULL,
	"Address_ID" integer NOT NULL   DEFAULT NEXTVAL(('"address_address_id_seq"'::text)::regclass),
	"Employee_ID" integer NULL,
	"Member_ID" integer NULL,
	CONSTRAINT "CHK_Address_Owner" CHECK (("Employee_ID" IS NOT NULL) OR ("Member_ID" IS NOT NULL))
)
;

CREATE TABLE "Attendance"
(
	"Entry_type" varchar(50) NULL,
	"Timestamp_entrance" timestamp without time zone NOT NULL,
	"Timestamp_exit" timestamp without time zone NULL,
	"Attendance_ID" integer NOT NULL   DEFAULT NEXTVAL(('"attendance_attendance_id_seq"'::text)::regclass),
	"Member_ID" integer NULL
)
;

CREATE TABLE "Certificate"
(
	"Acquisition_date" date NULL,
	"Certificate_number" smallint NOT NULL,
	"Description" text NULL,
	"File_path" text NULL,
	"Name" varchar(200) NOT NULL,
	"Publisher" varchar(200) NULL,
	"Type" varchar(200) NOT NULL,
	"Url" varchar(500) NULL,
	"Valid_to" date NOT NULL,
	"Certificate_ID" integer NOT NULL   DEFAULT NEXTVAL(('"certificate_certificate_id_seq"'::text)::regclass),
	"Employee_ID" integer NULL
)
;

CREATE TABLE "Discount_code"
(
	"Discount_percent" numeric(10,2) NOT NULL,
	"Expire_date" timestamp without time zone NOT NULL,
	"Name" varchar(50) NOT NULL,
	"Discount_code_ID" smallint NOT NULL   DEFAULT NEXTVAL(('"discount_code_discount_code_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Employee"
(
	"Bank_account_number" varchar(34) NOT NULL,
	"End_date" date NULL,
	"Position" varchar(200) NOT NULL,
	"Role" varchar(200) NULL,
	"Start_date" date NOT NULL,
	"Type_of_empoyment" varchar(50) NOT NULL,
	"Employee_ID" integer NOT NULL   DEFAULT NEXTVAL(('"employee_employee_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Lesson_template"
(
	"Description" text NULL,
	"Duration" smallint NOT NULL,
	"Maximum_capacity" smallint NOT NULL,
	"Name" varchar(200) NOT NULL,
	"Price" numeric(10,2) NOT NULL,
	"Lesson_template_ID" integer NOT NULL   DEFAULT NEXTVAL(('"lesson_template_lesson_template_id_seq"'::text)::regclass),
	"Lesson_type_ID" smallint NOT NULL
)
;

CREATE TABLE "Lesson_type"
(
	"Description" text NULL,
	"Name" varchar(100) NOT NULL,
	"Lesson_type_ID" smallint NOT NULL   DEFAULT NEXTVAL(('"lesson_type_lesson_type_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Lesson_type_Tariff"
(
	"Tariff_ID" smallint NOT NULL,
	"Lesson_type_ID" smallint NOT NULL
)
;

CREATE TABLE "Member"
(
	"Credit_balance" integer NOT NULL DEFAULT 0,
	"Email" varchar(300) NULL,
	"Entry_token" uuid NOT NULL DEFAULT gen_random_uuid(),
	"First_attendance" boolean NULL,
	"Is_active" boolean NULL,
	"Name" varchar(100) NOT NULL,
	"Phone_number" varchar(50) NULL,
	"Photo" text NULL,
	"Surname" varchar(100) NOT NULL,
	"Password_hash" varchar(200) NULL,
	"Role" varchar(50) NOT NULL DEFAULT 'member',
	"Member_ID" integer NOT NULL   DEFAULT NEXTVAL(('"member_member_id_seq"'::text)::regclass),
	"Account_ID" integer NULL
)
;

CREATE TABLE "Membership"
(
	"Creation_date" date NOT NULL,
	"Is_auto_renewal" boolean NULL,
	"Valid_from" timestamp without time zone NOT NULL,
	"Valid_to" timestamp without time zone NOT NULL,
	"Membership_ID" integer NOT NULL   DEFAULT NEXTVAL(('"membership_membership_id_seq"'::text)::regclass),
	"Member_ID" integer NOT NULL,
	"Tariff_ID" smallint NOT NULL
)
;

CREATE TABLE "Payment"
(
	"Amount" numeric(10,2) NULL,
	"Date" timestamp with time zone NULL,
	"Payment_details" text NULL,
	"Payment_type" varchar(50) NULL,
	"Status" varchar(50) NULL,
	"Payment_ID" integer NOT NULL   DEFAULT NEXTVAL(('"payment_payment_id_seq"'::text)::regclass),
	"Discount_code_ID" smallint NULL,
	"Member_ID" integer NULL,
	"Membership_ID" integer NULL
)
;

CREATE TABLE "Reservation"
(
	"Attendance" boolean NULL,
	"Guest_name" varchar(200) NULL,
	"Note" text NULL,
	"Status" varchar(50) NOT NULL,
	"Timestamp_creation" timestamp without time zone NOT NULL,
	"Timestamp_change" timestamp without time zone NULL,
	"Reservation_ID" integer NOT NULL   DEFAULT NEXTVAL(('"reservation_reservation_id_seq"'::text)::regclass),
	"Member_ID" integer NOT NULL,
	"Lesson_schedule_ID" integer NOT NULL
)
;

CREATE TABLE "Reservation_payment"
(
	"Payment_ID" integer NULL,
	"Reservation_ID" integer NULL
)
;

/*
 * POZNÁMKA K LOKICE PŘÍSTUPŮ A PLATEB ZA LEKCE (BUDOUCNOST):
 * 1. Lekce na Kredity:
 *    Má nastavenou "Price" > 0. Při tvorbě rezervace backend strhává kredity přímo z účtu člena (Member.Credit_balance).
 * 
 * 2. Lekce na Tarif / Permanentku (Základ pro V1):
 *    "Price" je NULL (nebo 0). Lekce má povinný Lesson_type_ID. Backend ověřuje přístup přes propojovací
 *    tabulku Lesson_type_Tariff -> zkontroluje, zda má uživatel aktivní zápis v tabulce Membership pro povolený Tarif.
 * 
 * 3. Open lekce (přístupné všem pouhou registrací):
 *    Využívá stejný systém tarifů jako bod 2. V tabulce Tariff bude vytvořen např. "Základní/Free tarif" s cenou 0.
 *    Každý nový Member ho dostane automaticky po registraci do tabulky Membership (řeší backend nebo trigger). 
 *    V Lesson_type_Tariff se pak tento bezplatný tarif propojí s "Open" typy lekcí. Není nutná změna ve struktuře DDL.
 */
CREATE TABLE "Lesson_schedule"
(
	"Description" text NULL,
	"Duration" smallint NOT NULL,
	"End_time" timestamp without time zone NULL,
	"Is_private" boolean NULL,
	"Maximum_capacity" smallint NOT NULL,
	"Name" varchar(200) NOT NULL,
	"Price" numeric(10,2) NULL, /* lekce se platí přes tarify/permanentky, cena lekce se nevyžaduje. Do budoucna: pokud vyplněno, lekce bude mít vlastní cenu v kreditech (např. privátní/speciální lekce mimo tarif). */
	"Start_time" timestamp without time zone NOT NULL,
	"Status" varchar(50) NOT NULL,
	"Lesson_schedule_ID" integer NOT NULL   DEFAULT NEXTVAL(('"lesson_schedule_lesson_schedule_id_seq"'::text)::regclass),
	"Employee_ID" integer NOT NULL,
	"Lesson_template_ID" integer NULL,
	"Lesson_type_ID" smallint NOT NULL
)
;

CREATE TABLE "Tariff"
(
	"Description" text NULL,
	"Name" varchar(100) NOT NULL,
	"Price" numeric(10,2) NOT NULL,
	"Tariff_ID" smallint NOT NULL   DEFAULT NEXTVAL(('"tariff_tariff_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Trainer_note"
(
	"Created_at" timestamp without time zone NULL,
	"Text" text NULL,
	"Trainer_note_ID" integer NOT NULL   DEFAULT NEXTVAL(('"trainer_note_trainer_note_id_seq"'::text)::regclass),
	"Employee_ID" integer NULL,
	"Member_ID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Account" ADD CONSTRAINT "PK_Account"
	PRIMARY KEY ("Account_ID")
;

ALTER TABLE "Address" ADD CONSTRAINT "PK_Address"
	PRIMARY KEY ("Address_ID")
;

ALTER TABLE "Attendance" ADD CONSTRAINT "PK_Attendance"
	PRIMARY KEY ("Attendance_ID")
;

ALTER TABLE "Certificate" ADD CONSTRAINT "PK_Certificate"
	PRIMARY KEY ("Certificate_ID")
;

ALTER TABLE "Discount_code" ADD CONSTRAINT "PK_Discount_code"
	PRIMARY KEY ("Discount_code_ID")
;

ALTER TABLE "Employee" ADD CONSTRAINT "PK_Employee"
	PRIMARY KEY ("Employee_ID")
;

ALTER TABLE "Lesson_template" ADD CONSTRAINT "PK_Lesson_template"
	PRIMARY KEY ("Lesson_template_ID")
;

ALTER TABLE "Lesson_type" ADD CONSTRAINT "PK_Lesson_type"
	PRIMARY KEY ("Lesson_type_ID")
;

ALTER TABLE "Lesson_type_Tariff" ADD CONSTRAINT "PK_Lesson_type_Tariff"
	PRIMARY KEY ("Tariff_ID", "Lesson_type_ID")
;

ALTER TABLE "Member" ADD CONSTRAINT "PK_Member"
	PRIMARY KEY ("Member_ID")
;

ALTER TABLE "Membership" ADD CONSTRAINT "PK_Membership"
	PRIMARY KEY ("Membership_ID")
;

ALTER TABLE "Payment" ADD CONSTRAINT "PK_Payment"
	PRIMARY KEY ("Payment_ID")
;

ALTER TABLE "Reservation" ADD CONSTRAINT "PK_Reservation"
	PRIMARY KEY ("Reservation_ID")
;

ALTER TABLE "Lesson_schedule" ADD CONSTRAINT "PK_Lesson_schedule"
	PRIMARY KEY ("Lesson_schedule_ID")
;

ALTER TABLE "Tariff" ADD CONSTRAINT "PK_Tariff"
	PRIMARY KEY ("Tariff_ID")
;

ALTER TABLE "Trainer_note" ADD CONSTRAINT "PK_Trainer_note"
	PRIMARY KEY ("Trainer_note_ID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Employee"
	FOREIGN KEY ("Employee_ID") REFERENCES "Employee" ("Employee_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Member"
	FOREIGN KEY ("Member_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Attendance" ADD CONSTRAINT "FK_Attendance_Member"
	FOREIGN KEY ("Member_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Certificate" ADD CONSTRAINT "FK_Certificate_Employee"
	FOREIGN KEY ("Employee_ID") REFERENCES "Employee" ("Employee_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Employee" ADD CONSTRAINT "FK_Employee_Member"
	FOREIGN KEY ("Employee_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_template" ADD CONSTRAINT "FK_Lesson_template_Lesson_type"
	FOREIGN KEY ("Lesson_type_ID") REFERENCES "Lesson_type" ("Lesson_type_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_type_Tariff" ADD CONSTRAINT "FK_Lesson_type_Tariff_Tariff"
	FOREIGN KEY ("Tariff_ID") REFERENCES "Tariff" ("Tariff_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_type_Tariff" ADD CONSTRAINT "FK_Lesson_type_Tariff_Lesson_type"
	FOREIGN KEY ("Lesson_type_ID") REFERENCES "Lesson_type" ("Lesson_type_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Member" ADD CONSTRAINT "FK_Member_Account"
	FOREIGN KEY ("Account_ID") REFERENCES "Account" ("Account_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Membership" ADD CONSTRAINT "FK_Membership_Member"
	FOREIGN KEY ("Member_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Membership" ADD CONSTRAINT "FK_Membership_Tariff"
	FOREIGN KEY ("Tariff_ID") REFERENCES "Tariff" ("Tariff_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Payment_Discount_code"
	FOREIGN KEY ("Discount_code_ID") REFERENCES "Discount_code" ("Discount_code_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Payment_Member"
	FOREIGN KEY ("Member_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Payment_Membership"
	FOREIGN KEY ("Membership_ID") REFERENCES "Membership" ("Membership_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reservation" ADD CONSTRAINT "FK_Reservation_Member"
	FOREIGN KEY ("Member_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reservation" ADD CONSTRAINT "FK_Reservation_Lesson_schedule"
	FOREIGN KEY ("Lesson_schedule_ID") REFERENCES "Lesson_schedule" ("Lesson_schedule_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reservation_payment" ADD CONSTRAINT "FK_Reservation_payment_Payment"
	FOREIGN KEY ("Payment_ID") REFERENCES "Payment" ("Payment_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reservation_payment" ADD CONSTRAINT "FK_Reservation_payment_Reservation"
	FOREIGN KEY ("Reservation_ID") REFERENCES "Reservation" ("Reservation_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_schedule" ADD CONSTRAINT "FK_Lesson_schedule_Employee"
	FOREIGN KEY ("Employee_ID") REFERENCES "Employee" ("Employee_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_schedule" ADD CONSTRAINT "FK_Lesson_schedule_Lesson_template"
	FOREIGN KEY ("Lesson_template_ID") REFERENCES "Lesson_template" ("Lesson_template_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lesson_schedule" ADD CONSTRAINT "FK_Lesson_schedule_Lesson_type"
	FOREIGN KEY ("Lesson_type_ID") REFERENCES "Lesson_type" ("Lesson_type_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Trainer_note" ADD CONSTRAINT "FK_Trainer_note_Employee"
	FOREIGN KEY ("Employee_ID") REFERENCES "Employee" ("Employee_ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Trainer_note" ADD CONSTRAINT "FK_Trainer_note_Member"
	FOREIGN KEY ("Member_ID") REFERENCES "Member" ("Member_ID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE account_account_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE address_address_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE attendance_attendance_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE certificate_certificate_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE discount_code_discount_code_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE employee_employee_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE lesson_template_lesson_template_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE lesson_type_lesson_type_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE member_member_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE membership_membership_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE payment_payment_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE reservation_reservation_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE lesson_schedule_lesson_schedule_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE tariff_tariff_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE trainer_note_trainer_note_id_seq INCREMENT 1 START 1
;
